export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  TOGGLE_SEARCH: "TOGGLE_SEARCH",
  CHANGE_IDS: "CHANGE_IDS",
  CHANGE_CURRENT_PAGE: "CHANGE_CURRENT_PAGE",
  PUSH_NOTIFICATION: "PUSH_NOTIFICATION",
};
